// ════════════════════════════════════════════════════════
//  BRIGHT MINDS — Question Data
//  3 age tiers × 6 worlds × 8 questions = 144 questions
// ════════════════════════════════════════════════════════

const AGE_TIERS = {
  1: {
    label: '4 – 5',
    emoji: '🌱',
    name: 'Little Explorer',
    greeting: 'Hello, Little Explorer!',
    sub: 'Ages 4–5 • Big fun learning!',
    bodyClass: 'tier-1',
    worlds: ['numbers', 'colors', 'feelings', 'animals', 'shapes', 'social'],
  },
  2: {
    label: '6 – 7',
    emoji: '🚀',
    name: 'Rising Star',
    greeting: 'Hello, Rising Star!',
    sub: 'Ages 6–7 • Level up your brain!',
    bodyClass: 'tier-2',
    worlds: ['abc', 'math', 'feelings', 'animals', 'science', 'social'],
  },
  3: {
    label: '8 – 10',
    emoji: '⚡',
    name: 'Super Thinker',
    greeting: 'Hello, Super Thinker!',
    sub: 'Ages 8–10 • Challenge yourself!',
    bodyClass: 'tier-3',
    worlds: ['reading', 'math2', 'science2', 'world', 'logic', 'social2'],
  },
};

// ════════════════════════════════════════════
//  TIER 1 WORLDS  (Ages 4–5)
// ════════════════════════════════════════════
const WORLDS = {

  // ── TIER 1 ──────────────────────────────
  numbers: {
    title: '🔢 Numbers',
    color: 'wc-a',
    tier: 1,
    desc: 'Count & learn!',
    questions: [
      { icon:'🍎🍎🍎', text:'How many apples?', sub:'Count them!',
        choices:[{e:'1️⃣',l:'1'},{e:'2️⃣',l:'2'},{e:'3️⃣',l:'3'},{e:'4️⃣',l:'4'}], answer:'3️⃣',
        praise:'Yes! 1, 2, 3 — three apples! 🍎',
        tip:'Point to each apple together and count out loud: one… two… three!' },
      { icon:'⭐⭐', text:'How many stars?', sub:'Count the shiny stars!',
        choices:[{e:'1️⃣',l:'1'},{e:'2️⃣',l:'2'},{e:'3️⃣',l:'3'},{e:'5️⃣',l:'5'}], answer:'2️⃣',
        praise:'Two stars — you\'re a star too! ⭐',
        tip:'Hold up two fingers. One star… two stars! Clap for each.' },
      { icon:'🐶🐶🐶🐶', text:'How many dogs?', sub:'Count the puppies!',
        choices:[{e:'2️⃣',l:'2'},{e:'3️⃣',l:'3'},{e:'4️⃣',l:'4'},{e:'5️⃣',l:'5'}], answer:'4️⃣',
        praise:'Four dogs! Woof woof woof woof! 🐶',
        tip:'Bark once for each dog — makes counting fun!' },
      { icon:'🌸🌸🌸', text:'How many flowers?', sub:'Count the pretty flowers!',
        choices:[{e:'1️⃣',l:'1'},{e:'2️⃣',l:'2'},{e:'3️⃣',l:'3'},{e:'4️⃣',l:'4'}], answer:'3️⃣',
        praise:'Three flowers — beautiful! 🌸',
        tip:'Tap a finger for each flower. Nice slow pace!' },
      { icon:'🍪', text:'You have 1 cookie. You get 1 more. How many now?', sub:'Use your fingers!',
        choices:[{e:'1️⃣',l:'1'},{e:'2️⃣',l:'2'},{e:'3️⃣',l:'3'},{e:'4️⃣',l:'4'}], answer:'2️⃣',
        praise:'1 + 1 = 2! Two yummy cookies! 🍪',
        tip:'Hold up one finger, then raise another. Count together!' },
      { icon:'🐱🐱🐱🐱🐱', text:'How many cats?', sub:'Count them all!',
        choices:[{e:'3️⃣',l:'3'},{e:'4️⃣',l:'4'},{e:'5️⃣',l:'5'},{e:'6️⃣',l:'6'}], answer:'5️⃣',
        praise:'Five cats! Meow meow meow meow meow! 🐱',
        tip:'Meow for each cat together — sillier = more memorable!' },
      { icon:'🎈🎈', text:'2 balloons pop. How many are left from 4?', sub:'Start with 4, take away 2!',
        choices:[{e:'1️⃣',l:'1'},{e:'2️⃣',l:'2'},{e:'3️⃣',l:'3'},{e:'0️⃣',l:'0'}], answer:'2️⃣',
        praise:'4 minus 2 = 2! Great thinking! 🎈',
        tip:'Hold up 4 fingers, fold down 2. Count what\'s left together!' },
      { icon:'🦋🦋🦋', text:'How many butterflies?', sub:'Count the wings!',
        choices:[{e:'2️⃣',l:'2'},{e:'3️⃣',l:'3'},{e:'4️⃣',l:'4'},{e:'5️⃣',l:'5'}], answer:'3️⃣',
        praise:'Three butterflies! Flutter flutter flutter! 🦋',
        tip:'Flap your arms like butterfly wings and count each one!' },
    ],
  },

  colors: {
    title: '🎨 Colors',
    color: 'wc-b',
    tier: 1,
    desc: 'Name the colors!',
    questions: [
      { icon:'🔴', text:'What color is this?', sub:'Look at the big circle!',
        choices:[{e:'🔴',l:'Red'},{e:'🔵',l:'Blue'},{e:'🟡',l:'Yellow'},{e:'🟢',l:'Green'}], answer:'🔴',
        praise:'Red! Like a fire truck! 🚒',
        tip:'Find something red in the room. Ask: what else is red?' },
      { icon:'🔵', text:'What color is this?', sub:'A cool, calm color!',
        choices:[{e:'🟣',l:'Purple'},{e:'🔵',l:'Blue'},{e:'🟢',l:'Green'},{e:'🟡',l:'Yellow'}], answer:'🔵',
        praise:'Blue — like the sky and the sea! 💙',
        tip:'Name blue things: sky, water, blueberries. Find something blue nearby!' },
      { icon:'🟡', text:'What color is this?', sub:'Bright like the sun!',
        choices:[{e:'🟠',l:'Orange'},{e:'🟤',l:'Brown'},{e:'🟡',l:'Yellow'},{e:'🟢',l:'Green'}], answer:'🟡',
        praise:'Yellow — sunny and bright! ☀️',
        tip:'Make a sun shape with your hands! Y-E-L-L-O-W, yellow!' },
      { icon:'🟢', text:'What color is this?', sub:'Like grass and frogs!',
        choices:[{e:'🔵',l:'Blue'},{e:'🟡',l:'Yellow'},{e:'🟢',l:'Green'},{e:'🔴',l:'Red'}], answer:'🟢',
        praise:'Green! Like leaves and frogs! 🐸',
        tip:'Ribbit like a frog! Find green things around you.' },
      { icon:'🟠', text:'What color is this?', sub:'Like a pumpkin!',
        choices:[{e:'🔴',l:'Red'},{e:'🟠',l:'Orange'},{e:'🟡',l:'Yellow'},{e:'🟤',l:'Brown'}], answer:'🟠',
        praise:'Orange! Like a pumpkin or a carrot! 🥕',
        tip:'Name orange things: carrots, oranges, pumpkins. Mix red + yellow = orange!' },
      { icon:'🟣', text:'What color is this?', sub:'A royal color!',
        choices:[{e:'🔵',l:'Blue'},{e:'🔴',l:'Red'},{e:'🟣',l:'Purple'},{e:'🟤',l:'Brown'}], answer:'🟣',
        praise:'Purple! The color of grapes and royalty! 👑',
        tip:'Purple is made by mixing red and blue! Can you name 2 purple things?' },
      { icon:'🩷', text:'What color is this?', sub:'A sweet, soft color!',
        choices:[{e:'🔴',l:'Red'},{e:'🩷',l:'Pink'},{e:'🟣',l:'Purple'},{e:'🟠',l:'Orange'}], answer:'🩷',
        praise:'Pink! Soft and sweet! 🌸',
        tip:'Pink is a lighter red! Find pink things in the room together.' },
      { icon:'🟤', text:'What color is this?', sub:'Like chocolate and mud!',
        choices:[{e:'🟠',l:'Orange'},{e:'⬛',l:'Black'},{e:'🟤',l:'Brown'},{e:'🔴',l:'Red'}], answer:'🟤',
        praise:'Brown — like chocolate cake! 🍫',
        tip:'Find brown things: wood, dirt, chocolate, hair. Yum!' },
    ],
  },

  feelings: {
    title: '😊 Feelings',
    color: 'wc-c',
    tier: 1,
    desc: 'How do you feel?',
    questions: [
      { icon:'😄', text:'This friend is feeling...', sub:'Look at that big smile!',
        choices:[{e:'😄',l:'Happy'},{e:'😢',l:'Sad'},{e:'😠',l:'Angry'},{e:'😨',l:'Scared'}], answer:'😄',
        praise:'Happy! That big smile shows happiness! 😄',
        tip:'Make a big happy smile together! Ask: when do YOU feel happy?' },
      { icon:'😢', text:'This friend is feeling...', sub:'Are there tears?',
        choices:[{e:'😄',l:'Happy'},{e:'😢',l:'Sad'},{e:'😮',l:'Surprised'},{e:'😴',l:'Sleepy'}], answer:'😢',
        praise:'Sad — and that\'s okay. We all feel sad sometimes. 🤗',
        tip:'Give a comforting hug. Ask: what helps you feel better when sad?' },
      { icon:'😠', text:'This friend is feeling...', sub:'Notice the eyebrows!',
        choices:[{e:'😄',l:'Happy'},{e:'😢',l:'Sad'},{e:'😠',l:'Angry'},{e:'🤔',l:'Thinking'}], answer:'😠',
        praise:'Angry — it\'s okay. Taking deep breaths helps! 😌',
        tip:'Talk about what makes us angry and what helps us calm down.' },
      { icon:'😮', text:'This friend is feeling...', sub:'That open mouth!',
        choices:[{e:'😮',l:'Surprised'},{e:'😴',l:'Sleepy'},{e:'😄',l:'Happy'},{e:'😨',l:'Scared'}], answer:'😮',
        praise:'Surprised! Oh wow, what a shock! 😮',
        tip:'Jump up surprised together! Share a time you were surprised.' },
      { icon:'😴', text:'This friend is feeling...', sub:'Droopy eyes!',
        choices:[{e:'😢',l:'Sad'},{e:'😴',l:'Sleepy'},{e:'😠',l:'Angry'},{e:'😄',l:'Happy'}], answer:'😴',
        praise:'Sleepy — time for a cozy nap! 😴',
        tip:'Yawn dramatically together! Talk about bedtime routines.' },
      { icon:'😨', text:'This friend is feeling...', sub:'Wide eyes!',
        choices:[{e:'😨',l:'Scared'},{e:'😄',l:'Happy'},{e:'😢',l:'Sad'},{e:'😮',l:'Surprised'}], answer:'😨',
        praise:'Scared — everyone feels scared sometimes! 🫂',
        tip:'Give a big reassuring hug. Ask: who do you go to when scared?' },
      { icon:'🥰', text:'This friend is feeling...', sub:'Hearts in the eyes!',
        choices:[{e:'😠',l:'Angry'},{e:'😢',l:'Sad'},{e:'🥰',l:'Loved'},{e:'😨',l:'Scared'}], answer:'🥰',
        praise:'Loved! You are so loved! 💕',
        tip:'Give a big hug! Ask: who makes you feel loved?' },
      { icon:'🤩', text:'This friend is feeling...', sub:'Stars in the eyes!',
        choices:[{e:'😴',l:'Sleepy'},{e:'😢',l:'Sad'},{e:'🤩',l:'Excited'},{e:'😠',l:'Angry'}], answer:'🤩',
        praise:'Excited! That sparkly feeling! ✨',
        tip:'Jump up and down excitedly together! Ask: what are you excited about?' },
    ],
  },

  animals: {
    title: '🐾 Animals',
    color: 'wc-d',
    tier: 1,
    desc: 'Who says that?',
    questions: [
      { icon:'🐶', text:'What sound does a dog make?', sub:'Wag that tail!',
        choices:[{e:'😺',l:'Meow'},{e:'🐕',l:'Woof!'},{e:'🐄',l:'Moo'},{e:'🐸',l:'Ribbit'}], answer:'🐕',
        praise:'Woof woof! You sound just like a dog! 🐶',
        tip:'Bark together! Ask: have you ever met a dog?' },
      { icon:'🐱', text:'What sound does a cat make?', sub:'Furry and soft!',
        choices:[{e:'🐕',l:'Woof'},{e:'😺',l:'Meow!'},{e:'🐄',l:'Moo'},{e:'🦆',l:'Quack'}], answer:'😺',
        praise:'Meow! You\'re a natural cat! 🐱',
        tip:'Purr and meow together! Ask if they\'ve ever petted a cat.' },
      { icon:'🐮', text:'What sound does a cow make?', sub:'Lives on a farm!',
        choices:[{e:'🐕',l:'Woof'},{e:'😺',l:'Meow'},{e:'🐄',l:'Moo!'},{e:'🐑',l:'Baa'}], answer:'🐄',
        praise:'Moooo! Cows give us milk! 🥛',
        tip:'Moo as loudly as you can together! Cows live on farms.' },
      { icon:'🐸', text:'Where does a frog live?', sub:'Think wet and green!',
        choices:[{e:'🏔️',l:'Mountain'},{e:'🌊',l:'Pond/water'},{e:'🏜️',l:'Desert'},{e:'❄️',l:'Snow'}], answer:'🌊',
        praise:'Near water! Frogs love ponds and puddles! 🐸',
        tip:'Jump like a frog! Ribbit ribbit — frogs love to swim!' },
      { icon:'🦁', text:'What animal is the king of the jungle?', sub:'Roar!',
        choices:[{e:'🐘',l:'Elephant'},{e:'🦒',l:'Giraffe'},{e:'🦁',l:'Lion'},{e:'🐆',l:'Cheetah'}], answer:'🦁',
        praise:'Lion! The king of the jungle! 👑',
        tip:'ROAR together as loudly as you can! Lions are very strong and brave.' },
      { icon:'🐘', text:'What is special about an elephant?', sub:'Look at its face!',
        choices:[{e:'🦕',l:'Long neck'},{e:'🦛',l:'Big horn'},{e:'🐘',l:'Big trunk'},{e:'🦒',l:'Spots'}], answer:'🐘',
        praise:'A long trunk! Elephants use it to drink water! 🐘',
        tip:'Dangle your arm like a trunk and make elephant sounds! Whooo!' },
      { icon:'🦋', text:'A butterfly starts life as a...', sub:'It changes and grows!',
        choices:[{e:'🐣',l:'Baby bird'},{e:'🐛',l:'Caterpillar'},{e:'🐟',l:'Fish'},{e:'🐝',l:'Bee'}], answer:'🐛',
        praise:'Caterpillar — then it grows beautiful wings! 🦋',
        tip:'Crawl like a caterpillar then spread your arms like butterfly wings!' },
      { icon:'🐦', text:'How do birds get around?', sub:'What do they use?',
        choices:[{e:'🏊',l:'Swimming'},{e:'🦅',l:'Flying'},{e:'🏃',l:'Running'},{e:'🚗',l:'Driving'}], answer:'🦅',
        praise:'Flying! Wings carry them through the sky! 🐦',
        tip:'Flap your arms like wings and soar around the room!' },
    ],
  },

  shapes: {
    title: '🔷 Shapes',
    color: 'wc-e',
    tier: 1,
    desc: 'Find the shape!',
    questions: [
      { icon:'🔵', text:'What shape is this?', sub:'Round and round!',
        choices:[{e:'⬛',l:'Square'},{e:'🔵',l:'Circle'},{e:'🔺',l:'Triangle'},{e:'▬',l:'Rectangle'}], answer:'🔵',
        praise:'Circle! Round like the sun! ☀️',
        tip:'Draw a circle in the air with your finger! What else is a circle?' },
      { icon:'🔺', text:'What shape is this?', sub:'1, 2, 3 corners!',
        choices:[{e:'🔵',l:'Circle'},{e:'⬛',l:'Square'},{e:'🔺',l:'Triangle'},{e:'⭐',l:'Star'}], answer:'🔺',
        praise:'Triangle! Three sides, three corners! 🔺',
        tip:'Make a triangle above your head with your hands. Count the sides!' },
      { icon:'⬛', text:'What shape is this?', sub:'Four equal sides!',
        choices:[{e:'🔺',l:'Triangle'},{e:'⬛',l:'Square'},{e:'🔵',l:'Circle'},{e:'⭐',l:'Star'}], answer:'⬛',
        praise:'Square! Four equal sides! ⬛',
        tip:'Trace a square with your finger on a flat surface. Find one in the room!' },
      { icon:'⭐', text:'What shape is this?', sub:'It shines at night!',
        choices:[{e:'🔵',l:'Circle'},{e:'🔺',l:'Triangle'},{e:'⭐',l:'Star'},{e:'🔷',l:'Diamond'}], answer:'⭐',
        praise:'Star! Twinkle twinkle! ⭐',
        tip:'Spread your fingers wide like a star! Sing twinkle twinkle together!' },
      { icon:'🔷', text:'What shape is this?', sub:'Like a tilted square!',
        choices:[{e:'⬛',l:'Square'},{e:'🔵',l:'Circle'},{e:'🔷',l:'Diamond'},{e:'🔺',l:'Triangle'}], answer:'🔷',
        praise:'Diamond! Shiny like a gem! 💎',
        tip:'Find diamond shapes — like a kite or a baseball field!' },
      { icon:'🟥', text:'What shape is this?', sub:'Longer on two sides!',
        choices:[{e:'⬛',l:'Square'},{e:'🟥',l:'Rectangle'},{e:'🔵',l:'Circle'},{e:'⭐',l:'Star'}], answer:'🟥',
        praise:'Rectangle! Like a door or a book! 📚',
        tip:'Find rectangles — books, doors, windows! Count the sides together.' },
      { icon:'🔵🔺⬛', text:'Which shape has NO corners?', sub:'Corners are pointy bits!',
        choices:[{e:'🔺',l:'Triangle'},{e:'⬛',l:'Square'},{e:'🔵',l:'Circle'},{e:'⭐',l:'Star'}], answer:'🔵',
        praise:'Circle! Smooth all the way round! 🔵',
        tip:'Run your finger around a circle — no bumps at all! So smooth!' },
      { icon:'🔺', text:'How many corners does a triangle have?', sub:'Count the pointy bits!',
        choices:[{e:'1️⃣',l:'1'},{e:'2️⃣',l:'2'},{e:'3️⃣',l:'3'},{e:'4️⃣',l:'4'}], answer:'3️⃣',
        praise:'Three corners — just like three sides! 🔺',
        tip:'Point to each corner together. One, two, three — triangle!' },
    ],
  },

  social: {
    title: '🤝 Friends',
    color: 'wc-f',
    tier: 1,
    desc: 'Be a good friend!',
    questions: [
      { icon:'🤝', text:'When you meet someone new, you...', sub:'What\'s friendly?',
        choices:[{e:'👋',l:'Say hello!'},{e:'😤',l:'Walk away'},{e:'😴',l:'Sleep'},{e:'🙈',l:'Hide'}], answer:'👋',
        praise:'Say hello! You\'re so friendly! 👋',
        tip:'Practice greeting: "Hi, my name is ___! Nice to meet you!" with a wave!' },
      { icon:'🍪🍪', text:'You have 2 cookies. Your friend has none. You...', sub:'Be kind!',
        choices:[{e:'😊',l:'Share one!'},{e:'🙅',l:'Keep both'},{e:'😤',l:'Run away'},{e:'😴',l:'Ignore'}], answer:'😊',
        praise:'Share! Sharing makes BOTH friends happy! 🍪',
        tip:'Practice sharing with a toy or snack. "Would you like some?"' },
      { icon:'😢', text:'Your friend is sad. You...', sub:'How can you help?',
        choices:[{e:'🤗',l:'Give a hug'},{e:'😂',l:'Laugh'},{e:'🏃',l:'Run away'},{e:'📺',l:'Ignore'}], answer:'🤗',
        praise:'Give a hug! You\'re such a kind friend! 🤗',
        tip:'Practice a gentle hug. Talk about how a hug helps someone feel better.' },
      { icon:'🗣️', text:'Someone is speaking. You...', sub:'Respectful listening!',
        choices:[{e:'👂',l:'Listen quietly'},{e:'📣',l:'Talk over them'},{e:'😴',l:'Fall asleep'},{e:'🏃',l:'Walk away'}], answer:'👂',
        praise:'Listen! Good listeners are great friends! 👂',
        tip:'Practice quiet listening. Make eye contact, nod — show you\'re listening!' },
      { icon:'🎮', text:'It\'s your friend\'s turn. You...', sub:'We all get a turn!',
        choices:[{e:'⏳',l:'Wait patiently'},{e:'😭',l:'Cry and grab'},{e:'😠',l:'Push them'},{e:'🏃',l:'Run away'}], answer:'⏳',
        praise:'Wait patiently — your turn is coming! ⏳',
        tip:'Practice waiting. Count to 10 slowly. "Your turn is almost here!"' },
      { icon:'🤕', text:'You bump your friend by accident. You say...', sub:'Oops!',
        choices:[{e:'😞',l:'Sorry!'},{e:'😤',l:'Nothing'},{e:'🏃',l:'Run away'},{e:'😂',l:'Laugh'}], answer:'😞',
        praise:'Sorry! Saying sorry is so brave! 💪',
        tip:'Practice "I\'m sorry, are you okay?" with a kind, gentle voice.' },
      { icon:'🎉', text:'Your friend wins a game. You say...', sub:'Good sportsmanship!',
        choices:[{e:'👏',l:'Well done!'},{e:'😠',l:'Get angry'},{e:'😭',l:'Sulk'},{e:'🙅',l:'Refuse'}], answer:'👏',
        praise:'Well done! Cheering for friends is wonderful! 👏',
        tip:'Clap and say "Well done!" Practice celebrating others!' },
      { icon:'🧸', text:'Your friend wants to try your toy. You...', sub:'Kindness time!',
        choices:[{e:'🤲',l:'Let them try'},{e:'🙅',l:'Always say no'},{e:'😠',l:'Get angry'},{e:'🏃',l:'Hide it'}], answer:'🤲',
        praise:'Share and take turns — that\'s so kind! 🧸',
        tip:'Practice: "You can have a turn, then I\'ll have mine." Take turns!' },
    ],
  },

  // ── TIER 2 ──────────────────────────────
  abc: {
    title: '🔤 Reading & Letters',
    color: 'wc-a',
    tier: 2,
    desc: 'Words & phonics!',
    questions: [
      { icon:'🍎', text:'"Apple" starts with which letter?', sub:'Sound it out — Ah…',
        choices:[{e:'A',l:'A'},{e:'B',l:'B'},{e:'C',l:'C'},{e:'D',l:'D'}], answer:'A',
        praise:'A is for Apple — great phonics! 🍎',
        tip:'Say the sound together: "Aaa — Apple!" List other A words: ant, art, arm.' },
      { icon:'🌞', text:'Which word rhymes with "cat"?', sub:'Same ending sound!',
        choices:[{e:'🐶',l:'Dog'},{e:'🎩',l:'Hat'},{e:'🌙',l:'Moon'},{e:'🌳',l:'Tree'}], answer:'🎩',
        praise:'Hat! Cat and hat rhyme — they end in -at! 🎩',
        tip:'Say them together: cat, hat, bat, mat, rat! Clap the rhyme.' },
      { icon:'🏠', text:'How many syllables in "house"?', sub:'Clap each syllable!',
        choices:[{e:'1️⃣',l:'1'},{e:'2️⃣',l:'2'},{e:'3️⃣',l:'3'},{e:'4️⃣',l:'4'}], answer:'1️⃣',
        praise:'1 syllable — "house" is one clap! 👏',
        tip:'Clap the word together: HOUSE — one clap! Try "rain-bow" — two claps!' },
      { icon:'🌈', text:'What is the FIRST letter of "rainbow"?', sub:'Look at the word carefully!',
        choices:[{e:'A',l:'A'},{e:'N',l:'N'},{e:'R',l:'R'},{e:'B',l:'B'}], answer:'R',
        praise:'R is for Rainbow — Rrr! 🌈',
        tip:'Spell R-A-I-N-B-O-W together, pointing to each letter.' },
      { icon:'⭐🌟', text:'Which two words begin with the same sound?', sub:'Listen carefully!',
        choices:[{e:'🐱🚗',l:'Cat & Car'},{e:'🐶🐟',l:'Dog & Fish'},{e:'🎩🌙',l:'Hat & Moon'},{e:'🏠🌹',l:'House & Rose'}], answer:'🐱🚗',
        praise:'Cat & Car both start with C! 🐱🚗',
        tip:'Say both words slowly: Caaaat… Caaar. Hear that C sound at the start?' },
      { icon:'📖', text:'Which word means the opposite of "big"?', sub:'Think of size!',
        choices:[{e:'🌳',l:'Tall'},{e:'🔴',l:'Red'},{e:'🐭',l:'Small'},{e:'💨',l:'Fast'}], answer:'🐭',
        praise:'Small is the opposite of big! 🐭',
        tip:'Name opposites together: big/small, hot/cold, fast/slow, day/night!' },
      { icon:'🐘', text:'How many syllables in "elephant"?', sub:'Clap as you say it!',
        choices:[{e:'2️⃣',l:'2'},{e:'3️⃣',l:'3'},{e:'4️⃣',l:'4'},{e:'1️⃣',l:'1'}], answer:'3️⃣',
        praise:'El-e-phant — three claps! 🐘',
        tip:'Clap it out: EL (clap) - E (clap) - PHANT (clap) = 3 syllables!' },
      { icon:'🍌', text:'Which word rhymes with "blue"?', sub:'Same -oo sound!',
        choices:[{e:'🍎',l:'Red'},{e:'👟',l:'Shoe'},{e:'🌳',l:'Green'},{e:'🐶',l:'Dog'}], answer:'👟',
        praise:'Blue and shoe rhyme! They end in -oo! 👟',
        tip:'List more -oo rhymes: blue, shoe, glue, new, zoo, too, who!' },
    ],
  },

  math: {
    title: '🔢 Math',
    color: 'wc-b',
    tier: 2,
    desc: 'Numbers & adding!',
    questions: [
      { icon:'🍕🍕🍕', text:'3 + 2 = ?', sub:'Count on from 3!',
        choices:[{e:'4️⃣',l:'4'},{e:'5️⃣',l:'5'},{e:'6️⃣',l:'6'},{e:'3️⃣',l:'3'}], answer:'5️⃣',
        praise:'3 + 2 = 5! Pizza time! 🍕',
        tip:'Hold up 3 fingers, then add 2 more. Count them all: 1,2,3,4,5!' },
      { icon:'🎈🎈🎈🎈🎈🎈', text:'6 – 2 = ?', sub:'Pop 2 balloons!',
        choices:[{e:'3️⃣',l:'3'},{e:'4️⃣',l:'4'},{e:'5️⃣',l:'5'},{e:'2️⃣',l:'2'}], answer:'4️⃣',
        praise:'6 – 2 = 4! Nice subtraction! 🎈',
        tip:'Count 6 fingers, fold down 2. Count what\'s left: 4!' },
      { icon:'🔢', text:'What number comes AFTER 9?', sub:'Think of the number line!',
        choices:[{e:'7️⃣',l:'7'},{e:'8️⃣',l:'8'},{e:'🔟',l:'10'},{e:'1️⃣1️⃣',l:'11'}], answer:'🔟',
        praise:'10! 9 then 10 — great counting! 🔢',
        tip:'Count together: 7, 8, 9… 10! High five on 10!' },
      { icon:'📦📦📦📦📦📦📦📦📦📦', text:'How many boxes? Count by 2s!', sub:'2, 4, 6…',
        choices:[{e:'8️⃣',l:'8'},{e:'9️⃣',l:'9'},{e:'🔟',l:'10'},{e:'1️⃣2️⃣',l:'12'}], answer:'🔟',
        praise:'10! Counting by 2s is fast! 10',
        tip:'Count by 2s together — clap on each number: 2, 4, 6, 8, 10!' },
      { icon:'🌡️', text:'Which number is GREATER: 7 or 4?', sub:'Which is bigger?',
        choices:[{e:'4️⃣',l:'4'},{e:'7️⃣',l:'7'},{e:'Same',l:'Same'},{e:'0️⃣',l:'0'}], answer:'7️⃣',
        praise:'7 is greater than 4! 7 > 4 🌡️',
        tip:'Use a number line or fingers. 7 is further along — so it\'s bigger!' },
      { icon:'🔢', text:'2 × 3 = ?', sub:'3 groups of 2!',
        choices:[{e:'4️⃣',l:'4'},{e:'5️⃣',l:'5'},{e:'6️⃣',l:'6'},{e:'7️⃣',l:'7'}], answer:'6️⃣',
        praise:'2 × 3 = 6! Multiplication magic! ✨',
        tip:'Draw 3 groups of 2 dots. Count them all: 2, 4, 6!' },
      { icon:'🎂', text:'Half of 10 is...', sub:'Split it equally!',
        choices:[{e:'4️⃣',l:'4'},{e:'5️⃣',l:'5'},{e:'6️⃣',l:'6'},{e:'3️⃣',l:'3'}], answer:'5️⃣',
        praise:'Half of 10 is 5! Great sharing! 🎂',
        tip:'Cut an imaginary cake in half. 10 ÷ 2 = 5 pieces each!' },
      { icon:'🕐', text:'What time does this clock show?', sub:'Short hand on 3, long hand on 12!',
        choices:[{e:'🕐',l:'1 o\'clock'},{e:'🕒',l:'3 o\'clock'},{e:'🕕',l:'5 o\'clock'},{e:'🕧',l:'12:30'}], answer:'🕒',
        praise:'3 o\'clock! You can read a clock! 🕒',
        tip:'Short (hour) hand points to 3. Long (minute) hand on 12 = o\'clock!' },
    ],
  },

  science: {
    title: '🔬 Science',
    color: 'wc-c',
    tier: 2,
    desc: 'Discover the world!',
    questions: [
      { icon:'☀️', text:'What does a plant need to grow?', sub:'Think about what helps it thrive!',
        choices:[{e:'🌑',l:'Darkness'},{e:'☀️💧',l:'Sun & water'},{e:'❄️',l:'Snow'},{e:'🔥',l:'Fire'}], answer:'☀️💧',
        praise:'Sun and water — plants love both! 🌱',
        tip:'Water a plant together if you have one! Talk about what it needs to grow.' },
      { icon:'🌡️', text:'Water turns into ice when it gets...', sub:'Think of winter!',
        choices:[{e:'🔥',l:'Very hot'},{e:'🌡️',l:'Very cold'},{e:'💨',l:'Very windy'},{e:'☀️',l:'Very sunny'}], answer:'🌡️',
        praise:'Very cold! Ice is frozen water! ❄️',
        tip:'Put water in the freezer and check it later! What happened?' },
      { icon:'🌍', text:'What shape is the Earth?', sub:'Look from outer space!',
        choices:[{e:'🔷',l:'Square'},{e:'🌍',l:'Round / sphere'},{e:'🔺',l:'Triangle'},{e:'▬',l:'Flat'}], answer:'🌍',
        praise:'Round like a ball — a sphere! 🌍',
        tip:'Find a ball and say "Earth is shaped like this!" Spin it like a planet!' },
      { icon:'🌦️', text:'What comes after dark clouds and lightning?', sub:'Look outside on a stormy day!',
        choices:[{e:'☀️',l:'Sunshine'},{e:'🌧️',l:'Rain'},{e:'🌈',l:'Rainbow'},{e:'❄️',l:'Snow'}], answer:'🌧️',
        praise:'Rain! Dark clouds bring rain! 🌧️',
        tip:'Watch the clouds together. Dark + thunder = rain coming! Splash in puddles after!' },
      { icon:'🧲', text:'What does a magnet do?', sub:'Think of sticking together!',
        choices:[{e:'💨',l:'Blows things'},{e:'🧲',l:'Attracts metal'},{e:'💧',l:'Makes it wet'},{e:'🔥',l:'Burns things'}], answer:'🧲',
        praise:'Magnets attract metal — they stick to it! 🧲',
        tip:'Find a magnet and test what it sticks to. Metal yes, plastic no!' },
      { icon:'🌙', text:'Why do we have day and night?', sub:'Think of the spinning Earth!',
        choices:[{e:'🌙',l:'Earth spins around'},{e:'☀️',l:'Sun moves'},{e:'🌍',l:'Earth stops'},{e:'⭐',l:'Stars blink'}], answer:'🌙',
        praise:'Earth spins! One side gets sun (day), one gets dark (night)! 🌍',
        tip:'Use a torch and a ball: shine on half = day, dark half = night!' },
      { icon:'🌱', text:'Which part of a plant makes food from sunlight?', sub:'The flat, green part!',
        choices:[{e:'🌿',l:'Leaf'},{e:'🌸',l:'Flower'},{e:'🌱',l:'Root'},{e:'🌳',l:'Trunk'}], answer:'🌿',
        praise:'Leaves make food using sunlight — photosynthesis! 🌿',
        tip:'Hold a leaf up to light. It captures sunlight to make food for the plant!' },
      { icon:'🦴', text:'What protects the brain inside your head?', sub:'Your body\'s armour!',
        choices:[{e:'🦷',l:'Teeth'},{e:'💪',l:'Muscle'},{e:'🦴',l:'Skull'},{e:'👁️',l:'Eye'}], answer:'🦴',
        praise:'The skull — your brain\'s helmet! 🦴',
        tip:'Tap gently on your head. That\'s your skull protecting your amazing brain!' },
    ],
  },

  // ── TIER 3 ──────────────────────────────
  reading: {
    title: '📖 Reading & Words',
    color: 'wc-a',
    tier: 3,
    desc: 'Vocabulary & comprehension',
    questions: [
      { icon:'📖', text:'What does "enormous" mean?', sub:'Choose the best meaning.',
        choices:[{e:'🐭',l:'Very small'},{e:'🏔️',l:'Very large'},{e:'💨',l:'Very fast'},{e:'🌡️',l:'Very hot'}], answer:'🏔️',
        praise:'Enormous means very, very large! 🏔️',
        tip:'Use it in a sentence: "An elephant is enormous." Ask them to use it too!' },
      { icon:'📝', text:'Which is a VERB (action word)?', sub:'What can you DO?',
        choices:[{e:'🏠',l:'House'},{e:'🏃',l:'Running'},{e:'🔵',l:'Blue'},{e:'😊',l:'Happy'}], answer:'🏃',
        praise:'Running is a verb — it\'s an action! 🏃',
        tip:'Sort words together: nouns (things), verbs (actions), adjectives (describing).' },
      { icon:'🌧️❄️', text:'Rain and snow are types of...', sub:'What\'s the category?',
        choices:[{e:'🍎',l:'Fruits'},{e:'🌦️',l:'Precipitation'},{e:'🐶',l:'Animals'},{e:'🔢',l:'Numbers'}], answer:'🌦️',
        praise:'Precipitation — water falling from the sky! 🌧️',
        tip:'List types: rain, snow, sleet, hail. All are precipitation!' },
      { icon:'📚', text:'In a story, who tells it? The...', sub:'Think of whose "voice" you hear.',
        choices:[{e:'🎭',l:'Villain'},{e:'📖',l:'Narrator'},{e:'🐉',l:'Monster'},{e:'🌟',l:'Hero'}], answer:'📖',
        praise:'The narrator tells the story! 📖',
        tip:'Read a book together and point out: "The narrator is telling us this!"' },
      { icon:'🌍', text:'A word that means the same as "happy" is called a...', sub:'Two words with similar meaning.',
        choices:[{e:'🔄',l:'Synonym'},{e:'↔️',l:'Antonym'},{e:'🔤',l:'Noun'},{e:'⚡',l:'Prefix'}], answer:'🔄',
        praise:'Synonym! Happy = joyful = cheerful — all synonyms! 🔄',
        tip:'List synonyms: big/large/huge, fast/quick/speedy, sad/unhappy/gloomy.' },
      { icon:'🐘🐜', text:'What does the prefix "mini" mean in "miniature"?', sub:'Think of mini vs mega!',
        choices:[{e:'🏔️',l:'Very big'},{e:'🐭',l:'Very small'},{e:'💨',l:'Very fast'},{e:'🌊',l:'Very wet'}], answer:'🐭',
        praise:'Mini means very small — like a miniature toy! 🐭',
        tip:'Explore prefixes: mini=small, mega=big, super=above, sub=under.' },
      { icon:'📖', text:'Which sentence has correct punctuation?', sub:'Check for capital & full stop.',
        choices:[{e:'A',l:'the dog runs'},{e:'B',l:'The dog runs.'},{e:'C',l:'the dog Runs.'},{e:'D',l:'The dog runs'}], answer:'B',
        praise:'Capital letter at start, full stop at end — perfect! ✅',
        tip:'Check: every sentence starts with a capital and ends with . ? or !' },
      { icon:'🗺️', text:'A story has a beginning, middle and...', sub:'Every story has three parts!',
        choices:[{e:'🔄',l:'Repeat'},{e:'⏭️',l:'End'},{e:'↩️',l:'Go back'},{e:'❓',l:'Question'}], answer:'⏭️',
        praise:'Beginning, middle, end — the three parts of every story! 📖',
        tip:'Retell a favourite story together using those three parts. Great literacy skill!' },
    ],
  },

  math2: {
    title: '➗ Maths',
    color: 'wc-b',
    tier: 3,
    desc: 'Multiply, divide & more!',
    questions: [
      { icon:'🔢', text:'5 × 4 = ?', sub:'Think of 5 groups of 4.',
        choices:[{e:'16',l:'16'},{e:'18',l:'18'},{e:'20',l:'20'},{e:'24',l:'24'}], answer:'20',
        praise:'5 × 4 = 20! Times tables power! 💪',
        tip:'Count by 5s: 5, 10, 15, 20 — four jumps!' },
      { icon:'🍕', text:'24 ÷ 4 = ?', sub:'Split 24 into 4 equal groups.',
        choices:[{e:'4',l:'4'},{e:'5',l:'5'},{e:'6',l:'6'},{e:'8',l:'8'}], answer:'6',
        praise:'24 ÷ 4 = 6! Division is sharing equally! 🍕',
        tip:'Draw 4 circles, deal out 24 dots one by one. Count each group!' },
      { icon:'📐', text:'What is the area of a 3×4 rectangle?', sub:'Area = length × width',
        choices:[{e:'7',l:'7'},{e:'12',l:'12'},{e:'14',l:'14'},{e:'10',l:'10'}], answer:'12',
        praise:'3 × 4 = 12 square units! Area! 📐',
        tip:'Draw it on paper: 3 rows of 4 squares = 12 squares total.' },
      { icon:'🔢', text:'What is 50% of 80?', sub:'Percent means "out of 100".',
        choices:[{e:'20',l:'20'},{e:'40',l:'40'},{e:'60',l:'60'},{e:'30',l:'30'}], answer:'40',
        praise:'50% of 80 = 40! Half of 80! 💯',
        tip:'50% = half. Half of 80 — split 80 into two equal groups = 40.' },
      { icon:'⏰', text:'A film starts at 3:15 and lasts 45 minutes. When does it end?', sub:'Add the minutes!',
        choices:[{e:'3:45',l:'3:45'},{e:'4:00',l:'4:00'},{e:'4:15',l:'4:15'},{e:'3:55',l:'3:55'}], answer:'4:00',
        praise:'3:15 + 45 mins = 4:00! 🎬',
        tip:'Count on: 3:15 + 45 min. First 15 min = 3:30, then 30 more = 4:00.' },
      { icon:'🔢', text:'Round 347 to the nearest 100.', sub:'Look at the tens digit!',
        choices:[{e:'300',l:'300'},{e:'350',l:'350'},{e:'400',l:'400'},{e:'340',l:'340'}], answer:'300',
        praise:'347 rounds to 300 — the tens digit 4 is less than 5! 🎯',
        tip:'Rule: tens digit 0-4 = round down, 5-9 = round up. 4 < 5 so round DOWN.' },
      { icon:'📊', text:'What is the median of: 3, 7, 2, 9, 5?', sub:'First put them in order!',
        choices:[{e:'5',l:'5'},{e:'7',l:'7'},{e:'3',l:'3'},{e:'9',l:'9'}], answer:'5',
        praise:'2, 3, 5, 7, 9 — the middle number is 5! 📊',
        tip:'Sort numbers smallest to largest, then find the middle one.' },
      { icon:'🔢', text:'Which number is a PRIME number?', sub:'Only divisible by 1 and itself!',
        choices:[{e:'9',l:'9'},{e:'6',l:'6'},{e:'11',l:'11'},{e:'4',l:'4'}], answer:'11',
        praise:'11 is prime — only 1×11 makes it! 🔢',
        tip:'Check: does anything divide into 11 evenly? No! So it\'s prime.' },
    ],
  },

  science2: {
    title: '🔬 Science',
    color: 'wc-c',
    tier: 3,
    desc: 'Deeper discoveries!',
    questions: [
      { icon:'🌍', text:'What is the main gas humans breathe in?', sub:'Every breath you take!',
        choices:[{e:'💨',l:'Carbon dioxide'},{e:'🌬️',l:'Oxygen'},{e:'🔥',l:'Hydrogen'},{e:'💧',l:'Water vapour'}], answer:'🌬️',
        praise:'Oxygen — we breathe it in and breathe out CO₂! 💨',
        tip:'Take a deep breath together! Trees give us oxygen — we give them CO₂!' },
      { icon:'🧬', text:'The basic unit of all living things is a...', sub:'Too small to see without a microscope!',
        choices:[{e:'🦴',l:'Bone'},{e:'🔬',l:'Cell'},{e:'🧠',l:'Brain'},{e:'🫀',l:'Heart'}], answer:'🔬',
        praise:'A cell! All life is made of cells! 🔬',
        tip:'A cell is like a tiny room with everything needed for life. Billions in you!' },
      { icon:'⚡', text:'What type of energy does the sun give us?', sub:'Feel it on your skin on a sunny day!',
        choices:[{e:'⚡',l:'Electrical'},{e:'☀️',l:'Solar / light'},{e:'💨',l:'Wind'},{e:'🌊',l:'Wave'}], answer:'☀️',
        praise:'Solar energy — light and heat from the sun! ☀️',
        tip:'Solar panels capture this! Ask: can you think of other energy sources?' },
      { icon:'🌊', text:'What causes tides in the ocean?', sub:'A force from space!',
        choices:[{e:'💨',l:'Wind'},{e:'🌡️',l:'Temperature'},{e:'🌙',l:'The Moon\'s gravity'},{e:'🐋',l:'Whales'}], answer:'🌙',
        praise:'The Moon\'s gravity pulls on Earth\'s oceans — tides! 🌙',
        tip:'The moon pulls water toward it. As Earth rotates we get high and low tides!' },
      { icon:'🧪', text:'In a chemical reaction, what is always conserved (saved)?', sub:'Nothing disappears — it just changes!',
        choices:[{e:'🌡️',l:'Temperature'},{e:'🎨',l:'Colour'},{e:'⚖️',l:'Mass'},{e:'💧',l:'Water'}], answer:'⚖️',
        praise:'Mass is always conserved — nothing is created or destroyed! ⚖️',
        tip:'Law of conservation of mass: weigh reactants and products — same weight!' },
      { icon:'🌱', text:'What process do plants use to make food?', sub:'Hint: they need sunlight and CO₂!',
        choices:[{e:'🍽️',l:'Digestion'},{e:'🌿',l:'Photosynthesis'},{e:'💧',l:'Evaporation'},{e:'🌬️',l:'Respiration'}], answer:'🌿',
        praise:'Photosynthesis — light + CO₂ + water = sugar + oxygen! 🌿',
        tip:'Photo = light, synthesis = making. Plants literally eat sunlight!' },
      { icon:'🔭', text:'What is the closest star to Earth?', sub:'We see it every day!',
        choices:[{e:'⭐',l:'Sirius'},{e:'☀️',l:'The Sun'},{e:'🌙',l:'The Moon'},{e:'🪐',l:'Jupiter'}], answer:'☀️',
        praise:'The Sun! It\'s our nearest star — just 8 light minutes away! ☀️',
        tip:'The next nearest star (Proxima Centauri) is 4 light YEARS away! The sun is SO close!' },
      { icon:'💧', text:'What are the three states of water?', sub:'Think of ice, water, and steam!',
        choices:[{e:'A',l:'Solid, liquid, gas'},{e:'B',l:'Ice, juice, cloud'},{e:'C',l:'Hot, cold, warm'},{e:'D',l:'River, lake, sea'}], answer:'A',
        praise:'Solid (ice), liquid (water), gas (steam) — three states! 💧',
        tip:'Heat ice = water, heat water = steam. Cool steam = water, cool water = ice!' },
    ],
  },

  world: {
    title: '🌍 World & People',
    color: 'wc-d',
    tier: 3,
    desc: 'Geography & society!',
    questions: [
      { icon:'🗺️', text:'What is the largest continent?', sub:'It contains China, India and Russia!',
        choices:[{e:'🌎',l:'Americas'},{e:'🌍',l:'Africa'},{e:'🌏',l:'Asia'},{e:'🇦🇺',l:'Australia'}], answer:'🌏',
        praise:'Asia! The biggest continent on Earth! 🌏',
        tip:'Find Asia on a map or globe. Name some countries: China, India, Japan!' },
      { icon:'🌊', text:'What is the largest ocean?', sub:'It covers more than a third of Earth!',
        choices:[{e:'🌊',l:'Pacific'},{e:'🌊',l:'Atlantic'},{e:'🌊',l:'Indian'},{e:'❄️',l:'Arctic'}], answer:'🌊',
        praise:'The Pacific Ocean — bigger than all land combined! 🌊',
        tip:'Find the Pacific on a map. It stretches from Asia all the way to the Americas!' },
      { icon:'🌡️', text:'Which continent is coldest on Earth?', sub:'Nearly all of it is ice!',
        choices:[{e:'❄️',l:'Antarctica'},{e:'🌏',l:'Asia'},{e:'🌎',l:'North America'},{e:'🌍',l:'Europe'}], answer:'❄️',
        praise:'Antarctica — the coldest, windiest place on Earth! 🐧',
        tip:'Penguins live there! It\'s even colder than the Arctic. Show it on a map!' },
      { icon:'🏛️', text:'What do we call the leader of a country who is elected by voters?', sub:'A democratic system!',
        choices:[{e:'👑',l:'King or Queen'},{e:'🗳️',l:'President or Prime Minister'},{e:'⚔️',l:'General'},{e:'🏛️',l:'Judge'}], answer:'🗳️',
        praise:'President or Prime Minister — chosen by voters! 🗳️',
        tip:'Talk about how elections work and why voting matters for everyone.' },
      { icon:'🏙️', text:'What is the capital city of France?', sub:'Famous for the Eiffel Tower!',
        choices:[{e:'🇮🇹',l:'Rome'},{e:'🇩🇪',l:'Berlin'},{e:'🇫🇷',l:'Paris'},{e:'🇪🇸',l:'Madrid'}], answer:'🇫🇷',
        praise:'Paris — the capital of France! 🗼',
        tip:'Find France on a map! Paris is famous for the Eiffel Tower and amazing food.' },
      { icon:'🌿', text:'Which human activity causes the MOST damage to rainforests?', sub:'Trees disappearing!',
        choices:[{e:'🌧️',l:'Rain'},{e:'🌲',l:'Deforestation'},{e:'💨',l:'Wind'},{e:'🐘',l:'Elephants'}], answer:'🌲',
        praise:'Deforestation — cutting down trees is the biggest threat! 🌿',
        tip:'Rainforests are home to over half of all species on Earth. Talk about why trees matter.' },
      { icon:'🤝', text:'What does the United Nations do?', sub:'Countries working together!',
        choices:[{e:'⚽',l:'Organises football'},{e:'🌍',l:'Promotes world peace'},{e:'💰',l:'Collects taxes'},{e:'🎬',l:'Makes films'}], answer:'🌍',
        praise:'The UN promotes peace and human rights for everyone! 🌍',
        tip:'The UN has 193 countries. Talk about why countries working together matters!' },
      { icon:'📜', text:'What is a human right that EVERYONE deserves?', sub:'Regardless of who you are!',
        choices:[{e:'🏆',l:'Winning trophies'},{e:'📚',l:'Access to education'},{e:'🚗',l:'Owning a car'},{e:'🎮',l:'Playing video games'}], answer:'📚',
        praise:'Education is a human right for every child on Earth! 📚',
        tip:'Talk about the UN Convention on the Rights of the Child — every child has rights!' },
    ],
  },

  logic: {
    title: '🧩 Logic & Thinking',
    color: 'wc-e',
    tier: 3,
    desc: 'Puzzles & problem solving!',
    questions: [
      { icon:'🔴🔵🔴🔵🔴', text:'What comes next in the pattern?', sub:'Look carefully at the sequence!',
        choices:[{e:'🔴',l:'Red'},{e:'🔵',l:'Blue'},{e:'🟡',l:'Yellow'},{e:'🟢',l:'Green'}], answer:'🔵',
        praise:'Blue! Red Blue Red Blue Red — Blue is next! 🔵',
        tip:'Patterns repeat! Read the sequence together and predict the next.' },
      { icon:'🧩', text:'All dogs are animals. Rex is a dog. Therefore Rex is...', sub:'Logical reasoning!',
        choices:[{e:'🐱',l:'A cat'},{e:'🐾',l:'An animal'},{e:'🐟',l:'A fish'},{e:'🦁',l:'A lion'}], answer:'🐾',
        praise:'An animal! If all dogs are animals, Rex MUST be an animal! 🐾',
        tip:'This is called a syllogism — a logical argument. Can you make your own?' },
      { icon:'🔢', text:'I am a number. Double me and add 3 to get 11. What am I?', sub:'Work backwards!',
        choices:[{e:'3',l:'3'},{e:'4',l:'4'},{e:'5',l:'5'},{e:'6',l:'6'}], answer:'4',
        praise:'4! Because 4×2=8, then 8+3=11! 🔢',
        tip:'Work backwards: 11 – 3 = 8, then 8 ÷ 2 = 4. Check: (4×2)+3=11 ✓' },
      { icon:'🏠', text:'If today is Wednesday, what day was it 3 days ago?', sub:'Count back on the week!',
        choices:[{e:'Mon',l:'Monday'},{e:'Sun',l:'Sunday'},{e:'Tue',l:'Tuesday'},{e:'Sat',l:'Saturday'}], answer:'Sun',
        praise:'Sunday! Wed → Tue → Mon → Sun! 📅',
        tip:'Count back: Wednesday, Tuesday, Monday, Sunday. Use your fingers!' },
      { icon:'⚖️', text:'Which is heavier: 1kg of feathers or 1kg of bricks?', sub:'Read carefully!',
        choices:[{e:'🪶',l:'Feathers'},{e:'🧱',l:'Bricks'},{e:'⚖️',l:'Same weight'},{e:'❓',l:'Impossible to know'}], answer:'⚖️',
        praise:'Same weight — both are 1kg! It\'s a famous trick question! ⚖️',
        tip:'This tricks lots of people! Weight is weight — 1kg is always 1kg.' },
      { icon:'💡', text:'A farmer has 17 sheep. All but 9 run away. How many are left?', sub:'Read very carefully!',
        choices:[{e:'8',l:'8'},{e:'9',l:'9'},{e:'17',l:'17'},{e:'0',l:'0'}], answer:'9',
        praise:'9! "All but 9" means 9 STAYED. Tricky wording! 💡',
        tip:'"All but 9" = all except 9. 9 sheep stayed. This tests reading carefully!' },
      { icon:'🔢', text:'What is the next number in: 2, 4, 8, 16, __?', sub:'How does each number grow?',
        choices:[{e:'18',l:'18'},{e:'24',l:'24'},{e:'32',l:'32'},{e:'20',l:'20'}], answer:'32',
        praise:'32! Each number doubles: ×2 each time! 🔢',
        tip:'2→4 (×2), 4→8 (×2), 8→16 (×2), 16→32 (×2). It\'s exponential growth!' },
      { icon:'🧩', text:'If you re-arrange "SILENT", you can spell...', sub:'Anagram puzzle!',
        choices:[{e:'A',l:'INSLET'},{e:'B',l:'LISTEN'},{e:'C',l:'TILENS'},{e:'D',l:'SNITEL'}], answer:'B',
        praise:'LISTEN! SILENT and LISTEN use the exact same letters! 🎧',
        tip:'Anagrams are words made from the same letters. Fun to find them!' },
    ],
  },

  social2: {
    title: '🌟 Life Skills',
    color: 'wc-f',
    tier: 3,
    desc: 'Real-world thinking!',
    questions: [
      { icon:'💬', text:'A friend says something unkind. The best response is...', sub:'Think before you react!',
        choices:[{e:'😠',l:'Say something meaner back'},{e:'💬',l:'Calmly tell them it hurt'},{e:'😭',l:'Cry and run away'},{e:'🤐',l:'Stay silent forever'}], answer:'💬',
        praise:'Calmly expressing how you feel is a superpower! 💬',
        tip:'Practice "I feel ___ when you say ___." Using "I" statements is very powerful!' },
      { icon:'📱', text:'Someone online asks for your home address. You...', sub:'Online safety first!',
        choices:[{e:'📍',l:'Share it immediately'},{e:'🔒',l:'Never share — tell a trusted adult'},{e:'🤷',l:'Ask why they want it'},{e:'📸',l:'Send a photo instead'}], answer:'🔒',
        praise:'Never share personal info online — always tell a trusted adult! 🔒',
        tip:'Personal info = name, address, school, phone. Keep it private!' },
      { icon:'🎯', text:'You\'re struggling with a hard task. Best thing to do?', sub:'Growth mindset!',
        choices:[{e:'🚫',l:'Give up immediately'},{e:'💪',l:'Try a different approach'},{e:'😴',l:'Ignore it forever'},{e:'😠',l:'Get frustrated and quit'}], answer:'💪',
        praise:'Try a different approach! "Not yet" is better than "I can\'t"! 💪',
        tip:'Talk about growth mindset — mistakes help our brain grow stronger!' },
      { icon:'💰', text:'You get £10 pocket money. Best thing to do?', sub:'Smart money thinking!',
        choices:[{e:'🍬',l:'Spend it all immediately'},{e:'💰',l:'Save some, spend some'},{e:'🎁',l:'Give it all away'},{e:'😴',l:'Lose it'}], answer:'💰',
        praise:'Save some, spend some! That\'s smart financial thinking! 💰',
        tip:'Introduce saving: even saving £2 of £10 = 20% saved. Great habit!' },
      { icon:'🕒', text:'You have homework, chores, and want to play. Best approach?', sub:'Time management!',
        choices:[{e:'🎮',l:'Play first, forget the rest'},{e:'📝',l:'Homework, chores, then play'},{e:'😴',l:'Do nothing'},{e:'😭',l:'Panic'}], answer:'📝',
        praise:'Homework first, then chores, then fun — responsibilities first! 📝',
        tip:'Make a simple schedule together. Ticking things off feels great!' },
      { icon:'♻️', text:'You see litter on the ground. You...', sub:'Being a responsible citizen!',
        choices:[{e:'🚶',l:'Walk past it'},{e:'♻️',l:'Pick it up and bin it'},{e:'😤',l:'Blame someone else'},{e:'🏃',l:'Run away'}], answer:'♻️',
        praise:'Pick it up! Small actions make a big difference! ♻️',
        tip:'Talk about environmental responsibility and community pride.' },
      { icon:'🤔', text:'Before making a big decision, you should...', sub:'Think it through!',
        choices:[{e:'⚡',l:'Act immediately'},{e:'😴',l:'Do nothing'},{e:'🤔',l:'Think about pros and cons'},{e:'😠',l:'Let someone else decide'}], answer:'🤔',
        praise:'Think about pros and cons — that\'s excellent decision making! 🤔',
        tip:'Make a simple pros/cons list together for a real decision they\'re facing.' },
      { icon:'🌍', text:'Which of these helps the environment MOST?', sub:'Green choices!',
        choices:[{e:'🚗',l:'Always drive everywhere'},{e:'🚿',l:'Long hot showers daily'},{e:'🌱',l:'Reduce, reuse, recycle'},{e:'🗑️',l:'Throw everything away'}], answer:'🌱',
        praise:'Reduce, reuse, recycle — the three Rs for a healthier planet! 🌱',
        tip:'Pick one green thing to do this week together. Small changes add up!' },
    ],
  },
};
